Inventory/urls.py
from django.conf.urls import url
from . import views
#TODO add examples for all urls
app_name = 'Inventory'


urlpatterns = [
    # /Inventory/
    url(r'^$', views.index, name='index'),
    #/Inventory/sites/
    url(r'^sites/$', views.site, name='sites'),
    # /Inventory/71/
    url(r'^(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    # /Inventory/site/add
    url(r'^site/add/$', views.create_site, name='site-add'),
    # /Inventory/site/2
    url(r'^site/(?P<pk>[0-9]+)/$', views.SiteUpdate.as_view(), name='site-update'),
    # /Inventory/site/2/delete
    url(r'^SiteClosed/(?P<pk>[0-9]+)/$', views.closed, name='closed'),
    # /Inventory/site/addDetails/
    url(r'^(?P<pk>[0-9]+)/AddDetails/', views.CreateDetail.as_view(), name='detail-create'),
    #
    url(r'^(?P<pk>[0-9]+)/updatedetails/', views.DetailUpdate.as_view(), name='detail-update'),
    #
    url(r'^devices/$', views.device, name='devices'),
    #
    url(r'^devices/add/$', views.create_device, name='devices_add'),
    #
    url(r'^devices/(?P<pk>[0-9]+)/$', views.DeviceToSite.as_view(), name='device_update'),
    #
    url(r'^devices/(?P<pk>[0-9]+)/delete/$', views.DeviceDelete.as_view(), name='device-delete'),
    #
    url(r'^sites/(?P<device_id>[0-9]+)/', views.remove_device, name='device_remove'),
    #
    url(r'^phones/add/$', views.CreatePhone.as_view(), name='phone_add'),
    #
    url(r'^phones/$', views.phone, name='phones'),
    #
    url(r'^sites/phone/(?P<phone_id>[0-9]+)/$', views.remove_phone, name='phone_remove'),
    #
    url(r'^phone/(?P<pk>[0-9]+)', views.PhoneToSite.as_view(), name='phonetosite'),
    #
    url(r'^phone/add/(?P<pk>[0-9]+)', views.UpdatePhone.as_view(), name='update-phone'),
    #
    url(r'^phone/delete/(?P<pk>[0-9]+)', views.DeletePhone.as_view(), name='delete-phone')
]


NetOps/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^netops/', include('Inventory.urls'))
]

Inventory/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Site(models.Model):
    siteCode = models.CharField(max_length=10, blank=False)
    city = models.CharField(max_length=30)
    state = models.CharField(max_length=30)
    address = models.CharField(max_length=100)
    zipcode = models.CharField(max_length=5)
    is_closed = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('Inventory:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.siteCode


class Config(models.Model):
    site = models.ForeignKey(Site, on_delete=models.CASCADE)
    service = ((' ', ' '),
               ("1.5 Mb T1 MPLS", "1.5 Mb T1 MPLS"),
               ('3 Mb T1 MPLS', '3 Mb T1 MPLS'),
               ('4.5 Mb MPLS', '4.5 Mb MPLS'),
               ('10 Mb MPLS', '10 Mb MPLS'),
               ('20 Mb MPLS', '20 Mb MPLS'),
               ('44 Mb MPLS', '44 Mb MPLS'),
               ('50 Mb MPLS', '50 Mb MPLS'),
               ('Broadband', 'Broadband'),
               )
    provider_C = ((" ", " "),
                  ("provider", "provider"),
                  ("provider1", "provider1"),
                  ("provider2", "provider2"),
                  )
    fw_tp = ((' ', ' '),
             ('fw1', 'fw1'),
             ('fw2', 'fw2'),
             )
    sw_tp = ((" ", " "),
             ("sw1", "sw1"),
             ("sw2", "sw2"),
             ("sw3", "sw3"),
             ("sw4", "sw4"),
             )

    provider = models.CharField(max_length=50, choices=provider_C, blank=True)
    circuit_id = models.CharField(max_length=200, blank=True)
    svc_id = models.CharField(max_length=200, choices=service, blank=True)
    prefix = models.CharField(max_length=200, blank=True)
    wan_net = models.CharField(max_length=200, blank=True)
    wan_remote = models.CharField(max_length=200, blank=True)
    wan_local = models.CharField(max_length=200, blank=True)
    name_fw = models.CharField(max_length=200, blank=True)
    fw_type = models.CharField(max_length=200, choices=fw_tp, blank=True)
    name_sw = models.CharField(max_length=200, default='')
    sw_type = models.CharField(max_length=200, choices=sw_tp, blank=True)
    fw_lan = models.CharField(max_length=200, blank=True)
    sw_lan = models.CharField(max_length=200, blank=True)
    fw_lo = models.CharField(max_length=200, blank=True)
    sw_lo = models.CharField(max_length=200, blank=True)
    peer_asn = models.CharField(max_length=200, blank=True)
    local_asn = models.CharField(max_length=200, blank=True)
    ospf_area = models.CharField(max_length=200, blank=True)
    cre_date = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('Inventory:detail', kwargs={'pk': Config.pk,
                                                   'detail_pk': self.pk})

    def __str__(self):
        return self.name_fw


class Device(models.Model):
    device = models.ForeignKey(Site, null=True, on_delete=models.SET_NULL, blank=True)
    serial = models.CharField(max_length=100)
    mac_add = models.CharField(max_length=30)
    device_name = models.CharField(max_length=40)
    firm_ver = models.CharField(max_length=40)
    hard_type = models.CharField(max_length=50)
    asset_tag = models.CharField(max_length=50, default='None')

    def __str__(self):
        return self.device_name


class Phone(models.Model):
    d_tp = ((' ', ' '),
            )

    site = models.ForeignKey(Site, null=True, on_delete=models.SET_NULL, blank=True)
    device_name = models.CharField(max_length=100, unique=True)
    desc = models.CharField(max_length=200)
    device_pool = models.CharField(max_length=200)
    device_type = models.CharField(max_length=40, choices=d_tp, blank=True)
    dir_num = models.CharField(max_length=10)

    def __str__(self):
        return self.desc

Inventory/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.http import JsonResponse
from django.db.models import Q
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse_lazy
from django.views import generic
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from .models import Site, Config, Device, Phone
from .form import UserForm, SiteForm, ConfigForm, DeviceForm
#TODO add comments for class and def funtions
#TODO clean up Imports


def index(request):
    return render(request, 'Inventory/index.html')


def create_site(request):
    form = SiteForm(request.POST or None)
    if request.POST:
        t = request.POST.get("siteCode")
        if form.is_valid():
            sites = form.save(commit=False)
            try:
                Site.objects.get(siteCode=t)
                context = {
                    'sites': sites,
                    'form': form,
                    'error_message': "Site Code already Used"
                }
                return render(request, 'Inventory/site_form.html', context)
            except Site.DoesNotExist:
                sites.save()
                return render(request, 'Inventory/detail.html', {'site': sites})

    context = {
        "form": form,
    }
    return render(request, 'Inventory/site_form.html', context)


class SiteUpdate(UpdateView):
    model = Site
    fields = ['siteCode', 'city', 'state', 'address', 'zipcode']


class CreateDetail(CreateView):
    model = Config
    fields = [
        'site', 'provider', 'circuit_id', 'svc_id', 'prefix', 'wan_net', 'wan_remote', 'wan_local', 'name_fw',
        'fw_type', 'name_sw', 'sw_type', 'fw_lan', 'sw_lan', 'fw_lo', 'sw_lo', 'peer_asn', 'local_asn',
        'ospf_area'
    ]
    success_url = '/netops/sites'


def delete_detail(request, pk, detail_id):
    sites = get_object_or_404(Site, pk)
    for details in Config.objects.get(pk=detail_id):
        details.delete()
    return render(request, 'Inventory/detail.html', {'sites': sites})


def detail(request, pk):
    sites = get_object_or_404(Site, pk=pk)
    return render(request, 'Inventory/detail.html', {'site': sites})


class DetailUpdate(UpdateView):
    model = Config
    fields = [
        'site', 'provider', 'circuit_id', 'svc_id', 'prefix', 'wan_net', 'wan_remote', 'wan_local', 'name_fw',
        'fw_type', 'name_sw', 'sw_type', 'fw_lan', 'sw_lan', 'fw_lo', 'sw_lo', 'peer_asn', 'local_asn',
        'ospf_area'
    ]
    success_url = '/netops/sites'


def closed(request, pk):
    sites = get_object_or_404(Site, pk=pk)
    if sites.is_closed:
        sites.is_closed = False
        sites.save()
        return render(request, 'Inventory/sites.html', {'success_message': 'Site is Reactivated'})

    else:
        sites.is_closed = True
        sites.save()
        return render(request, 'Inventory/sites.html', {'success_message': 'Site is now Closed'})


def site(request):
    sites = Site.objects.filter()
    details = Site.objects.all()
    query = request.GET.get("q")
    if query:
        sites = sites.filter(
            Q(siteCode__contains=query) |
            Q(city__contains=query) |
            Q(config__svc_id__icontains=query)
        ).distinct()
        return render(request, 'Inventory/sites.html', {'sites': sites,
                                                        'details': details})
    else:
        return render(request, 'Inventory/sites.html', {'sites': sites})


def device(request):
    devices = Device.objects.filter()
    query = request.GET.get("q")
    if query:
        devices = devices.filter(
            Q(device__address__icontains=query) |
            Q(mac_add__icontains=query) |
            Q(serial__icontains=query) |
            Q(hard_type=query) |
            Q(asset_tag=query)
        ).distinct()
        return render(request, 'Inventory/devices.html', {'object_list': devices})
    else:
        devices = Device.objects.all()
        return render(request, 'Inventory/devices.html', {'object_list': devices})


def create_device(request):
    form = DeviceForm(request.POST or None)
    if request.POST:
        t = request.POST.get("serial")
        if form.is_valid():
            devices = form.save(commit=False)
            try:
                Device.objects.get(serial=t)
                context = {
                    'Device': devices,
                    'form': form,
                    'error_message': "Serial already Used"
                }
                return render(request, 'Inventory/device_form.html', context)
            except Device.DoesNotExist:
                devices.save()
                return render(request, 'Inventory/devices.html', {'devices': devices})

    context = {
        "form": form,
    }
    return render(request, 'Inventory/device_form.html', context)


class DeviceToSite(UpdateView):
    model = Device
    fields = ['device', 'device_name']
    success_url = '/netops/devices'


class DeviceDelete(DeleteView):
    model = Device
    success_url = reverse_lazy('Inventory:devices')


def remove_device(request, device_id):
    devices = Device.objects.get(pk=device_id)
    t = devices.device.pk
    if devices.device is not None:
        devices.device = None
        devices.save()
        return detail(request, pk=t)


class CreatePhone(CreateView):
    model = Phone
    fields = ['site', 'device_name', 'desc', 'device_pool', 'device_type', 'dir_num']
    success_url = reverse_lazy('Inventory:phones')


def phone(request):
    phones = Phone.objects.filter()
    query = request.GET.get("q")
    if query:
        phones = phones.filter(
            Q(device_name__icontains=query) |
            Q(desc__icontains=query) |
            Q(device_pool__icontains=query) |
            Q(device_type__icontains=query) |
            Q(dir_num__icontains=query)
        ).distinct()
        return render(request, 'Inventory/phones.html', {'object_list': phones})
    else:
        phones = Phone.objects.all()
        return render(request, 'Inventory/phones.html', {'object_list': phones})


def remove_phone(request, phone_id):
    phones = Phone.objects.get(pk=phone_id)
    t = phones.site.pk
    if phones.site is not None:
        phones.site = None
        phones.save()
        return detail(request, pk=t)


class PhoneToSite(UpdateView):
    model = Phone
    fields = ['site', 'device_name', 'device_pool']
    success_url = '/netops/phones'


class UpdatePhone(UpdateView):
    model = Phone
    fields = ['site', 'device_name', 'desc', 'device_pool', 'dir_num']
    success_url = '/netops/phones'


class DeletePhone(DeleteView):
    model = Phone
    success_url = reverse_lazy('Inventory:phones')

templates/Inventory/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}NetOps{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Audiowide' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'inventory/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link rel="icon" type="image/png" href="{% static 'favicon.png' %}">


</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'Inventory:index' %}">NetOps</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block site_active %}{% endblock %}">
                    <a href="{% url 'Inventory:sites' %}">
                        <span class="glyphicon glyphicon-road" aria-hidden="true"></span>&nbsp; Sites
                    </a>
                </li>
                <li class="{% block Device_active %}{% endblock %}">
                    <a href="{% url 'Inventory:devices' %}">
                        <span class="glyphicon glyphicon-tasks" aria-hidden="true"></span>&nbsp; Devices
                    </a>
                </li>
                <li class="{% block Phone_active %}{% endblock %}">
                    <a href="{% url 'Inventory:phones' %}">
                        <span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>&nbsp; Phones
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="{% block siteAdd_active %}{% endblock %}">
                    <a href="{% url 'Inventory:site-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Site
                    </a>
                </li>
                <li class="{% block DeviceAdd_active %}{% endblock %}">
                    <a href="{% url 'Inventory:devices_add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Device
                    </a>
                </li>
                <li class="{% block PhoneAdd_active %}{% endblock %}">
                    <a href="{% url 'Inventory:phone_add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Phone
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; logout
                    </a>
                </li>
            </ul>

        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/Inventory/config_form.html
{% extends 'Inventory/base.html' %}
{% block title %}Edit Details{% endblock %}

{% block body %}

    <div class="container-fluid">

        <div class="row">
            <div class="col-sm-12 col-md-6">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>Details</h3>
                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}
                        <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <div class="form-group">
                                <div class="col-sm-offset-2  col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>

            </div>

        </div>

    </div>
{% endblock %}

templates/Inventory/detail.html
{% extends 'Inventory/base.html' %}
{% block title%}Site Details{% endblock %}
{% block site_active %}active{% endblock %}
{% block body %}
<div class="container-fluid detail-container">

    <div class="row">

        <!-- Left Site Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'Inventory:detail' site.id %}">
                        <h3> No Map Available </h3>
                    </a>
                <h1>{{ site.city }}, {{ site.state }} <br><small>{{ site.siteCode }}</small></h1>
                <h2>{{ site.address }} {{ site.zipcode }}</h2>

                <!-- Update Site -->
                <a href="{% url 'Inventory:site-update' site.id %}" class="btn btn-primary btn-sn" role="button">Update Site</a>
                </div>

            </div>

        </div>

        <!-- Right Detail Info -->
        <div class="col-sm-8 col-md-9">
            <div class="row">
                <div class="col-sm-6 col-md-7">
                    <ul class="nav nav-pills" style="margin-bottom: 10px;">
                        <li role="presentation"><a href="{% url 'Inventory:detail-create' site.id %}">Add Details</a> </li>
                        <li role="presentation"><a href="#">Delete Details</a> </li>
                    </ul>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Details</h3>
                    <table class="table">
                        <thead>
                        <tr></tr>

                        </thead>
                        <tr>
                            <th>provider</th>
                            {% for detail in site.config_set.all %}
                                <td>{{ detail.provider}}<br></td>
                            {% endfor %}
                        </tr>
                        <tr>
                            <th>circuit_id</th>
                            {% for detail in site.config_set.all %}
                                <td>{{ detail.circuit_id}}<br></td>
                            {% endfor %}
                        </tr>
                        <tr>
                            <th>svc_id</th>
                            {% for detail in site.config_set.all %}
                                <td>{{ detail.svc_id}}<br></td>
                            {% endfor %}
                        </tr>
                        <tr>
                            <th>prefix</th>
                            {% for detail in site.config_set.all %}
                                <td>{{ detail.prefix}}<br></td>
                            {% endfor %}
                        </tr>
                        <tr>
                            <th>wan_net</th>
                            {% for detail in site.config_set.all %}
                                <td>{{ detail.wan_net}}<br></td>
                            {% endfor %}
                        </tr>
                        <tr>
                            <th>wan_remote</th>
                            {% for detail in site.config_set.all %}
                                <td>{{ detail.wan_remote}}<br></td>
                            {% endfor %}
                        </tr>
                        <tr>
                            <th>wan_local</th>
                            {% for detail in site.config_set.all %}
                                <td>{{ detail.wan_local}}<br></td>
                            {% endfor %}
                        </tr>
                        <tr>
                            <th>name_fw</th>
                            {% for detail in site.config_set.all %}
                                <td>{{ detail.name_fw}}<br></td>
                            {% endfor %}
                        </tr>
                        <tr>
                            <th>fw_type</th>
                            {% for detail in site.config_set.all %}
                                <td>{{ detail.fw_type}}<br></td>
                            {% endfor %}
                        </tr>
                        <tr>
                            <th>name_sw</th>
                            {% for detail in site.config_set.all %}
                                <td>{{ detail.name_sw}}<br></td>
                            {% endfor %}
                        </tr>
                        <tr>
                            <th>sw_type</th>
                            {% for detail in site.config_set.all %}
                                <td>{{ detail.sw_type}}<br></td>
                            {% endfor %}
                        </tr>
                        <tr>
                            <th>fw_lan</th>
                            {% for detail in site.config_set.all %}
                                <td>{{ detail.fw_lan}}<br></td>
                            {% endfor %}
                        </tr>
                        <tr>
                            <th>sw_lan</th>
                            {% for detail in site.config_set.all %}
                                <td>{{ detail.sw_lan}}<br></td>
                            {% endfor %}
                        </tr>
                        <tr>
                            <th>fw_lo</th>
                            {% for detail in site.config_set.all %}
                                <td>{{ detail.fw_lo}}<br></td>
                            {% endfor %}
                        </tr>
                        <tr>
                            <th>sw_lo</th>
                            {% for detail in site.config_set.all %}
                                <td>{{ detail.sw_lo}}<br></td>
                            {% endfor %}
                        </tr>
                        <tr>
                            <th>peer_asn</th>
                            {% for detail in site.config_set.all %}
                                <td>{{ detail.peer_asn}}<br></td>
                            {% endfor %}
                        </tr>
                        <tr>
                            <th>local_asn</th>
                            {% for detail in site.config_set.all %}
                                <td>{{ detail.local_asn}}<br></td>
                            {% endfor %}
                        </tr>
                        <tr>
                            <th>ospf_area</th>
                            {% for detail in site.config_set.all %}
                                <td>{{ detail.ospf_area}}<br></td>
                            {% endfor %}
                        </tr>
                        <tr>
                            <th></th>
                            {% for detail in site.config_set.all %}
                                <td>
                                    <form action="{% url 'Inventory:detail-update' detail.id %}" method="get" style="display: inline;">
                                            {% csrf_token %}
                                            <input type="hidden" name="detail_id" value="{{ detail.id }}" />
                                            <button type="submit" class="btn btn-warning btn-xs">
                                                <span class="glyphicon glyphicon-plus"></span>&nbsp; update curcit
                                            </button>
                                        </form>
                                </td>
                            {% endfor %}
                        </tr>
                    </table>

                </div>

            </div>
        </div>
    </div>
    <div>
        <div class="panel panel-default">
                <h3> Network Devices</h3>
                <div class="panel-body "style="max-height: 10px;min-height: 200px;overflow-y: scroll">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Device Name</th>
                                <th>Serial</th>
                                <th>Asset Tag</th>
                                <th>Mac Address</th>
                                <th>Firmware Version</th>
                                <th>Hardware Type</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for device in site.device_set.all %}
                                <td>{{ device.device_name }}</td>
                                <td>{{ device.serial }}</td>
                                <td>{{ device.asset_tag }}</td>
                                <td>{{ device.mac_add }}</td>
                                <td>{{ device.firm_ver }}</td>
                                <td>{{ device.hard_type }}</td>
                                <td>
                                    <form action="{% url 'Inventory:device_remove' device.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="device_id" value="{{ device.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Remove from site
                                        </button>
                                    </form>
                                </td>
                                <tr></tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
    </div>
            <div class="panel panel-default">
                <h3> Phones</h3>
                <h4>Total Phones: {{ site.phone_set.all.count }}</h4>
                <div class="panel-body "style="max-height: 10px;min-height: 200px;overflow-y: scroll">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Device Name</th>
                                <th>Description</th>
                                <th>Device Pool</th>
                                <th>Device Type</th>
                                <th>Directory Number</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for phone in site.phone_set.all %}
                                <td>{{ phone.device_name }}</td>
                                <td>{{ phone.desc }}</td>
                                <td>{{ phone.device_pool }}</td>
                                <td>{{ phone.device_type }}</td>
                                <td>{{ phone.dir_num }}</td>
                                <td>
                                    <form action="{% url 'Inventory:phone_remove' phone.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="phone_id" value="{{ phone.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Remove phone from site
                                        </button>
                                    </form>
                                </td>
                                <tr></tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
    </div>
</div>
</div>
{% endblock %}

templates/Inventory/device_form.html
{% extends 'Inventory/base.html' %}
{% block title %}Details{% endblock %}
{% block DeviceAdd_active %}active{% endblock %}

{% block body %}

    <div class="container-fluid">

        <div class="row">
            <div class="col-sm-12 col-md-6">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>Device</h3>
                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}
                        <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'Inventory/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2  col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>

            </div>

        </div>

    </div>
{% endblock %}

templates/Inventory/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>

{% endfor %}

templates/Inventory/index.html
{% extends 'Inventory/base.html' %}



{% block body %}
    
    <center><img src="https://media.giphy.com/media/xT9DPJcpQqpR6icVCE/giphy-downsized-large.gif" align="middle"></center>
{% endblock %}

templates/Inventory/redirect.html
{% extends 'Inventory/base.html' %}
{% if success_message %}
    <p><strong>{{ success_message }}</strong></p>
{% endif %}
<meta http-equiv="refresh" content="3;{% url 'Inventory:sites' %}">